[project]
name = "movieverseml"
version = "0.1.0"
description = "Python microservice for movie recommendations."
authors = [
    {name = "haswe",email = "josuee152@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
